# yaml-language-server: $schema=https://software.backbase.eu/schema.json
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: retail-banking-universal-app
  description: Angular Web application for Retail Universal
  annotations:
    jfrog/release-repo: backbase-releases
    jfrog/release-path: com/backbase/apps
    jfrog/release-name: retail-banking-universal-app
    slack/conversation-id: C0108T6JSGY
    jira/maint-component: Retail Banking - Web App
    jira/maint-subcomponent: Universal Retail App
    jira/project-key: WEB2
    jira/project-component: 'Web: Retail App'
    backbase.io/documentation: retail-banking-universal
    sonarqube.org/project-key: cloud/baas-devops-reference_backbase-banking-apps
  tags:
    - angular
    - typescript
    - web
    - retail
spec:
  type: web-app
  lifecycle: production
  owner: RE - Web Warriors
